### PR TITLE
fixed some typos and clone text

### PR DESCRIPTION
**Pull request by salman-shah2022**

### CODE REVIEW

**Comment by eaglewarrior** [comment]
@salman-shah2022  I can merge it but wont count for hacktoberfest contribution as here u have to submit code as per issue

**Comment by salman-shah2022** [comment]
> @salman-shah2022  I can merge it but wont count for hacktoberfest contribution as here u have to submit code as per issue

First of all I fixed those typos because I have find them very headachable.I am not doing that for hacktorberfest.I was expecting a thank you note instead of that.Still Thanks):

**Comment by salman-shah2022** [comment]
> @salman-shah2022  I can merge it but wont count for hacktoberfest contribution as here u have to submit code as per issue

Yeah sure.I am learning machine learning and I happened to be on your repo.Found these spelling errors to be annoying and thus I forked your repo.And pull requests are just requests so its upto you if you consider mine PR worth merging.If you do merged my PR.Please say few nice words as it motivates me instead of what you just wrote.Thanks):

**Comment by eaglewarrior** [comment]
Thanks for your contribution

**Pull request merged**
